# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

jobs:
  - job: BuildReleaseAPK
    displayName: 'Build Release APK'
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          echo "text in not initialized!"
        displayName: Print Error Message

      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          tasks: 'assembleRelease'

